In [1]:
import torch

In [2]:
# let's build our first Tensor and check its shape
t1 = torch.tensor([[0,1,2], [3,4,5], [6,7,8]])
t1 = torch.tensor([[[1,2], [3,4]], [[5,6], [7,8]], [[9,10], [11,12]]])
print('t1: {}'.format(t1))
print('t1 shape: {}'.format(t1.shape))
print('t1 dtype: {}\n'.format(t1.dtype))

# alternatively
t1 = torch.arange(9).view(3, 3)

# can also define t1 as a FloatTensor
t1 = torch.arange(9.).view(3, -1)
print('t1: {}'.format(t1))
print('t1 dtype: {}\n'.format(t1.dtype))

# generate a (3,3) Tensor with all ones
t2 = torch.ones(3, 3)
print('t2: {}'.format(t2))
print('t2 shape: {}\n'.format(t2.shape))

# generate a (3,) Tensor with all zeros
t3 = torch.zeros(3)
print('t3: {}'.format(t3))
print('t3 shape: {}\n'.format(t3.shape))

# (n,) Tensors can be reshaped to (n,1) or (1,n) to allow operations requiring bidimensional Tensors
t3r = t3.view(3, 1)
print('t3r: {}'.format(t3r))
print('t3r shape: {}\n'.format(t3r.shape))

# can create higher dimensional Tensors
t4 = torch.arange(24).view(2,3,4)
print('t4: {}'.format(t4))
print('t4 shape: {}\n'.format(t4.shape))

t1: tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
t1 shape: torch.Size([3, 2, 2])
t1 dtype: torch.int64

t1: tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
t1 dtype: torch.float32

t2: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t2 shape: torch.Size([3, 3])

t3: tensor([0., 0., 0.])
t3 shape: torch.Size([3])

t3r: tensor([[0.],
        [0.],
        [0.]])
t3r shape: torch.Size([3, 1])

t4: tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
t4 shape: torch.Size([2, 3, 4])



In [3]:
# perform some basic operation on Tensor
print('sum:\n {}\n'.format(t1 + t2))
print('element-wise product:\n {}\n'.format(t1 * t2))
print('matrix product:\n {}\n'.format(torch.mm(t1, t2)))
print('exp:\n {}\n'.format(torch.exp(t1))) # sin, cos, log, etc. can be performed similarly
# in general NumPy 

sum:
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

element-wise product:
 tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

matrix product:
 tensor([[ 3.,  3.,  3.],
        [12., 12., 12.],
        [21., 21., 21.]])

exp:
 tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00],
        [2.0086e+01, 5.4598e+01, 1.4841e+02],
        [4.0343e+02, 1.0966e+03, 2.9810e+03]])



In [4]:
# some indexing
t5 = torch.arange(15.).view(5, 3)
print(t5)
print(t5[1, 2])  # element [1, 2]
print(t5[1, :])  # row 1
print(t5[1:5, :])  # rows 1 to 4
print(t5[1:5, 2:])  # submatrix of elements [x, y] s.t. 1 <= x < 5 and 2 <= y
print(t5[[1, 1, 3], [0, 2, 1]])  # (3,) Tensor with elements [1, 0], [1, 2] and [3, 1]
mask = torch.ByteTensor([[1, 0, 0], [0, 0, 1], [1, 1, 0], [1, 1, 1], [0, 0, 0]])
print(t5[mask])  # elements [x, y] wherever mask[x, y] == 1

# in general NumPy-like indexing works: https://docs.scipy.org/doc/numpy/user/basics.indexing.html

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])
tensor(5.)
tensor([3., 4., 5.])
tensor([[ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])
tensor([[ 5.],
        [ 8.],
        [11.],
        [14.]])
tensor([ 3.,  5., 10.])
tensor([ 0.,  5.,  6.,  7.,  9., 10., 11.])


In [10]:
import time
# device choice (runs only if you have CUDA enabled)
t6 = torch.rand(1000, 1000)  # 100 * 100 = 10000 random numbers in [0, 1)
t7 = torch.rand(1000, 4000)
print('t6 device: {}'.format(t6.device))
print('t7 device: {}'.format(t7.device))

start = time.time()
t6.mm(t7)
print('t6.mm(t7) total time (CPU): {} sec'.format(time.time() - start))

# now let's send the tensors in the GPU (this takes some time at first)
t6 = t6.to('cuda')
t7 = t7.to('cuda')
print('t6 device: {}'.format(t6.device))
print('t7 device: {}'.format(t7.device))

start = time.time()
t6.mm(t7)
print('t6.mm(t7) total time (GPU): {} sec'.format(time.time() - start))

t6 device: cpu
t7 device: cpu
t6.mm(t7) total time (CPU): 0.03164339065551758 sec
t6 device: cuda:0
t7 device: cuda:0
t6.mm(t7) total time (GPU): 0.0001480579376220703 sec
